### ISSUE TITLE
[BUG] Lemmeknow can not exclude or include tags

### ISSUE THREAD

**Issue by bee-san** [bee-san/Ares#116]
There is like 7 lemmeknow configs and none of them can exclude or include tags:

https://github.com/bee-san/Ares/pull/114

We should concentrate all of the configs into 1 config and figure out how to actually edit the config

**Comment by swanandx** [comment]
Because we are still using default config haha, the updated configs aren't used.

https://github.com/bee-san/Ares/blob/main/src/checkers/lemmeknow_checker.rs

**Comment by bee-san** [comment]
@swanandx Did you see the PR I linked? #114

**Comment by swanandx** [comment]
> @swanandx Did you see the PR I linked? #114 

Yup! We are still using that `IDENTIFIER` declared at top!

**Comment by bee-san** [comment]
Ahhhhh we areee :( How would you do it?

**Comment by swanandx** [comment]
> Ahhhhh we areee :( How would you do it?

replace `IDENTIFIER.identify` with `self.lemmeknow_config.identify`?
