### ISSUE TITLE
[BUG] Morse code is broken

### ISSUE THREAD

**Issue by bee-san** [bee-san/Ares#124]
I do not think it likes line feeds and I think a lot of delimiters are not supported, we should add them!

**Comment by oddron** [comment]
In morse_code.rs, there is a conflict between test cases `test_morse_code_both_new_line_and_carrage_return` and `test_morse_code_line_feed`.

`test_morse_code_both_new_line_and_carrage_return` requires line feeds to be ignored.

`test_morse_code_line_feed` requires a line feed to produce a space in the output.

What shall `\n` and `\r` map to in the output? (I would propose to map them to spaces)

**Comment by SkeletalDemise** [comment]
Fixed by #281
