### ISSUE TITLE
[FEATURE] Implement cargo-dist for easier building of `.exe` files etc

### ISSUE THREAD

**Issue by bee-san** [bee-san/Ares#195]
https://crates.io/crates/cargo-dist

**Comment by SkeletalDemise** [comment]
This would be great for our releases and CI. Most people won't want to install Rust and build Ares. We saw this with Ciphey and lots of people having trouble installing it. Since Rust is compiled unlike Python, we can easily make cross-platform binaries that people can download and use easily.

**Comment by bee-san** [comment]
> This would be great for our releases and CI. Most people won't want to install Rust and build Ares. We saw this with Ciphey and lots of people having trouble installing it. Since Rust is compiled unlike Python, we can easily make cross-platform binaries that people can download and use easily.

I am normally **super** against this, but how would you feel about Ares making an API call to the GitHub releases API to detect if it's the latest version or not? That way people can be alerted and can update it :) 

I hate the idea of a CLI app making an API call, but we can probably enable people to disable it somehow

**Comment by SkeletalDemise** [comment]
Yes, I think that's fine. I've seen open source projects on GitHub do that as a way to implement an updater. Using our own server would be worse for privacy and GitHub is more trustworthy (at least compared to a random person).
