### ISSUE TITLE
Aarch64/Arm64 Linux version

### ISSUE THREAD

**Issue by gregorni** [bee-san/Ares#242]
It would be nice to have an aarch64/arm64 Linux binary as part of the releases. Then people with Raspberry Pis or users of Asahi Linux could also use the program.

**Comment by gregorni** [comment]
As far as I can tell, only this line would have to be edited:

https://github.com/bee-san/Ares/blob/71973ddddb50074ca405f09431458c3ffadc6d27/Cargo.toml#L74

Changed to: `targets = ["x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-pc-windows-msvc", "aarch64-apple-darwin"]`

I'm not an expert, though.

**Comment by SkeletalDemise** [comment]
Linux aarch64 isn't supported by cargo-dist. The four target platforms in `Cargo.toml` are all the supported ones by cargo-dist.

https://opensource.axo.dev/cargo-dist/book/config.html?highlight=targets#targets

**Comment by SkeletalDemise** [comment]
I don't want to maintain a separate workflow just for Linux aarch64. You should make an issue on cargo-dist's repo. I'm closing this as `wontfix`
