### ISSUE TITLE
Did ares 0.10.0 get re-tagged?

### ISSUE THREAD

**Issue by chenrui333** [bee-san/Ares#256]
While trying to upgrade rust to 1.70.0, I found that the [ares 0.10.0 artifact got changed](https://github.com/Homebrew/homebrew-core/pull/132849), raise this issue to confirm if there was a re-tag happening. Thanks!

**Comment by SkeletalDemise** [comment]
Yes, I wasn't aware that Homebrew updated that quickly. Homebrew sniped the old release before I deleted it that day from trying to get cargo-dist to work. 👀

**Comment by chenrui333** [comment]
no worries, just want to confirm :) Thanks for the quick response, appreciate it! (we do ship things pretty fast 😄 )
