### ISSUE TITLE
[BUG]Docker build falied

### ISSUE THREAD

**Issue by keyiis** [bee-san/Ares#262]
` docker build .`
 => ERROR [builder 7/7] RUN cargo build --release                                                                  0.4s
------
 > [builder 7/7] RUN cargo build --release:
#13 0.352 error: failed to parse manifest at `/app/ares/Cargo.toml`
#13 0.352
#13 0.352 Caused by:
#13 0.352   feature `strip` is required
#13 0.352
#13 0.352   The package requires the Cargo feature called `strip`, but that feature is not stabilized in this version of Cargo (1.57.0 (b2e52d7ca 2021-10-21)).
#13 0.352   Consider trying a newer version of Cargo (this may require the nightly release).
#13 0.352   See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#profile-strip-option for more information about the status of this feature.

**Comment by SkeletalDemise** [comment]
>The package requires the Cargo feature called strip, but that feature is not stabilized in this version of Cargo (1.57.0 (b2e52d7ca 2021-10-21)).

Your Cargo version is too old, it's from 2021. Run `rustup update`
