### ISSUE TITLE
[Question] Is this repo still active?

### ISSUE THREAD

**Issue by yatzbim** [bee-san/Ares#278]
Looks like there are a bunch of open pull requests and that nothing has been merged in two months. Is this project still being actively contributed to? If it is then I'm interested in contributing, but I want to make sure that my PRs aren't made in vain.

Thanks,

**Comment by bee-san** [comment]
Hey! Kind of. The CI is broken, which means we have lost trust in approving pull requests so frequently. 

We have tried to fix the CI but the job is a bit bigger than we'd hoped for :( 

A lot of the PRs are just dependabot complaining about out-dated dependencies, and the rest we discuss in discord.

If you make a PR we'll review it :) I'm currently working on fixing our discord bot too, which you won't see reflected in this repo :(

**Comment by SkeletalDemise** [comment]
Hello. The CI was fixed and PRs are being merged. Ares is an active project, Ciphey isn't.

We welcome new contributors! There are a lot of issues that need to be closed and decoders to make.

I'm going to close this now as your question was answered.
