### ISSUE TITLE
Proposal: Paths

### ISSUE THREAD

**Issue by bee-san** [bee-san/Ares#79]
# Problem

When Ares goes Caesar -> Base64 -> Morse Code, we don't actually report this ordering. It's important we do as it's useful information!

# What should this look like?

I think a final solution should look like:

```
Encryption methods used:
Caesar → Base64 → MorseCode
```

However, we should have a flag or consider this format:

```
Encryption methods used:
1. Caesar - Uryyb
2. Base64 - VXJ5eWI=
3. Morse Code - ...- -..- .--- ..... . .-- .. -...-
```

It is hard counting how many decodings there was, and in a CTF you might get asked "what was the 3rd encoding used?"

The text on the right is the text _before_ it's decoded by the decoding function on the left.

We can easily add the numbers using a flag, but the text is bit harder to add -- especially if it is very long. Perhaps for a file output?

# How can we do this?

We can create a struct containing both the encrypted text and the decoders used:

```
struct Text {
    text: &str,
    decoding_path: Vec<&str>
}
```

Where `decoding_path` is an array of decoders like `["Caesar", "Base64"]`.

In the future to add support for text as above, we can make text into an array too (but not now!)

>  reason is that, when creating new crackresult, we don't know about previous decodings used unless passed down from function argument, and if we want to pass it anyway, why not just keep it with text, that way we could return the same struct from bfs! ( name the struct plz haha )

**Comment by SkeletalDemise** [comment]
Completed with #80.
