### ISSUE TITLE
[BUG] Timer bugs

### ISSUE THREAD

**Issue by bee-san** [bee-san/Ares#94]
From #93 

- [x]  Get timeout duration from config
- [ ]  Change return type to return an TimeOutError ??
- [x] ```            recv(result_recv) -> exit_result => {
                 // if we find an element that matches our exit condition, return it!
                 // technically this won't check if the initial string matches our exit condition
                 // but this is a demo and i'll be lazy :P
                 let exit_result = exit_result.ok(); // convert Result to Some
                 if exit_result.is_some() {
                     trace!("Found exit result: {:?}", exit_result);
                     return exit_result;
                 }
             },```
- [x] This error can be nicer `error!("TIMEOUT!!!");`
- [x] Create CLI argument for timeout

**Comment by bee-san** [comment]
For good first issue you can make a CLI argument to add the timeout, the timeout exists in our config right now :)

**Comment by butimnotashark** [comment]
Been a wild week , And learning how to accomplish this efficiently as well {I'm a Noob}... As well as feel like i need to rub my face across the code of ares as to not bork anything. Lol

**Comment by bee-san** [comment]
> Been a wild week , And learning how to accomplish this efficiently as well {I'm a Noob}... As well as feel like i need to rub my face across the code of ares as to not bork anything. Lol

👋🏻  Super sorry to be annoying but I implemented this yesterday 🙈   https://github.com/bee-san/Ares/pull/128

This is a nice-ish issue if you're interested? Instead of returning None we need to create a `DecoderResult` struct that says the input was already the plaintext and return it :) 

https://github.com/bee-san/Ares/issues/133

**Comment by butimnotashark** [comment]
> > Been a wild week , And learning how to accomplish this efficiently as well {I'm a Noob}... As well as feel like i need to rub my face across the code of ares as to not bork anything. Lol
> 
> 👋🏻 Super sorry to be annoying but I implemented this yesterday 🙈 #128
> 
> This is a nice issue if you're interested? Instead of returning None we need to create a `DecoderResult` struct that says the input was already the plaintext and return it :)
> 
> #133

No worries, Im a slow noob too @.@ . I'll look at that and give it a shot. Haha eventually ill be useful ~
